<a href="https://colab.research.google.com/github/weiyuchen1213/CE888/blob/master/Lab1_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Create a (4 x 2) integer array and print it's attributes

In [6]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


##2. Create an array of dimension (1,10) and sort it in ascending and descending order

In [21]:
a = np.array([1,23,45,67,8,66,79,81,95,33])
sorted_arry =np.sort(a)
reverse_arry = sorted_arry[::-1]
print(sorted_arry)
print(reverse_arry)


[ 1  8 23 33 45 66 67 79 81 95]
[95 81 79 67 66 45 33 23  8  1]


##3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [22]:
a = np.array([1,23,45,67,8,66,79,81,95,33])
b = np.reshape(a ,(-1,2))
print(b)

[[ 1 23]
 [45 67]
 [ 8 66]
 [79 81]
 [95 33]]


##4. Stack two arrays of any size horizontally and vertically


In [24]:
a = np.array([[12, 33], [2, 3],[45,87]])
b = np.array([[5, 6],[11,99]])
np.concatenate((a, b), axis=0)

array([[12, 33],
       [ 2,  3],
       [45, 87],
       [ 5,  6],
       [11, 99]])


## 5. Create two array of same size and find commom elements

In [42]:
a = [11,22,33,44,55]
b = [55,44,66,77,88]
print(set(a).intersection(set(b)))

{44, 55}


##6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [56]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
print(A)

print(A.max(axis=0))
print(A.max(axis=1))

print(A.min(axis=0))
print(A.min(axis=1))



[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[7 8]
[2 4 6 8]
[1 2]
[1 3 5 7]


##7. Create an array of size 100 and  compute the mean, median, standard deviation. 

In [83]:
import numpy as np
x= np.random.randint(100,size=(5,5))
print("Average:")
mean = x.mean()
print(mean)
print("Standard deviation:")
std = x.std()
print(std)
median= np.median(x)
print('median:')
print(median)


Average:
47.32
Standard deviation:
28.21591040530147
median:
45.0


##8. Normalize a 5x5 random matrix 

In [79]:
x= np.random.randint(50,size=(5,5))
print(x)

[[16 44 13 19 47]
 [ 7 13 43 25 28]
 [ 8 11 14  1 30]
 [43  9 46  7  0]
 [ 3 28  4 46  8]]


##9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [90]:
a = np.random.randint(1,10,(4,4,3))
print(a)
b = np.random.randint(1,10,(4,4))
print(b)
new = a*b[:,:,None]
print(new)

[[[3 6 9]
  [9 1 5]
  [2 5 2]
  [7 4 1]]

 [[9 9 4]
  [6 7 5]
  [4 8 9]
  [5 2 8]]

 [[1 5 3]
  [1 5 1]
  [5 9 9]
  [6 6 6]]

 [[7 1 2]
  [8 6 6]
  [9 1 6]
  [6 3 7]]]
[[8 1 4 4]
 [3 2 1 2]
 [9 6 8 3]
 [3 4 8 4]]
[[[24 48 72]
  [ 9  1  5]
  [ 8 20  8]
  [28 16  4]]

 [[27 27 12]
  [12 14 10]
  [ 4  8  9]
  [10  4 16]]

 [[ 9 45 27]
  [ 6 30  6]
  [40 72 72]
  [18 18 18]]

 [[21  3  6]
  [32 24 24]
  [72  8 48]
  [24 12 28]]]
