<a href="https://colab.research.google.com/github/weiyuchen1213/CE888/blob/master/my_recommender_finishcode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [0]:
#Ref:https://stackoverflow.com/questions/34091877/how-to-add-header-row-to-a-pandas-dataframe
jester_df = pd.read_csv("https://raw.githubusercontent.com/weiyuchen1213/CE888/master/Lab5/jester-data-1.csv", delimiter = ",", header=None)
jester_df

df_del = jester_df.drop(jester_df.columns[0],axis=1) #Columns "74" 
df_del

1      2      3      4     5    ...    96     97     98     99     100
0      -7.82   8.79  -9.66  -8.16 -7.52  ...  99.00  -5.63  99.00  99.00  99.00
1       4.08  -0.29   6.36   4.37 -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
2      99.00  99.00  99.00  99.00  9.03  ...  99.00  99.00  99.00  99.00  99.00
3      99.00   8.35  99.00  99.00  1.80  ...  99.00  99.00  99.00  99.00  99.00
4       8.50   4.61  -4.17  -5.39  1.36  ...   1.55   3.11   6.55   1.80   1.60
...      ...    ...    ...    ...   ...  ...    ...    ...    ...    ...    ...
24978   0.44   7.43   9.08   2.33  3.20  ...   9.03   6.55   8.69   8.79   7.43
24979   9.13  -8.16   8.59   9.08  0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24980  99.00  99.00  99.00  99.00 -7.77  ...  99.00  99.00  99.00  99.00  99.00
24981  99.00  99.00  99.00  99.00 -9.71  ...  99.00  99.00  99.00  99.00  99.00
24982   2.43   2.67  -3.98   4.27 -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 100 columns]

In [0]:
arr = df_del.values
print(arr.shape)

(24983, 100)


In [0]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1810455 (1810455,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [0]:
arr

array([[-7.82,  8.79, -9.66, ..., 99.  , 99.  , 99.  ],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [ 2.43,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

In [0]:
new_arr

array([[-7.82,  8.79, -9.66, ..., 99.  , 99.  , 99.  ],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32, 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  ,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

In [0]:
arr[idx[0][0], idx[1][0]]

6.7

In [0]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
latent_item_features

array([[0.364, 0.994],
       [0.821, 0.019],
       [0.128, 0.687],
       [0.267, 0.435],
       [0.653, 0.244],
       [0.012, 0.867],
       [0.423, 0.477],
       [0.441, 0.247],
       [0.675, 0.252],
       [0.565, 0.953],
       [0.403, 0.644],
       [0.585, 0.331],
       [0.188, 0.162],
       [0.116, 0.9  ],
       [0.271, 0.516],
       [0.528, 0.67 ],
       [0.63 , 0.132],
       [0.771, 0.582],
       [0.63 , 0.287],
       [0.775, 0.896],
       [0.428, 0.736],
       [0.094, 0.33 ],
       [0.61 , 0.589],
       [0.278, 0.718],
       [0.7  , 0.321],
       [0.207, 0.057],
       [0.16 , 0.511],
       [0.98 , 0.34 ],
       [0.495, 0.203],
       [0.093, 0.829],
       [0.432, 0.68 ],
       [0.663, 0.936],
       [0.166, 0.674],
       [0.766, 0.782],
       [0.175, 0.169],
       [0.354, 0.075],
       [0.792, 0.939],
       [0.23 , 0.642],
       [0.375, 0.135],
       [0.926, 0.496],
       [0.801, 0.003],
       [0.553, 0.005],
       [0.253, 0.927],
       [0.5

In [0]:
latent_user_preferences

array([[0.272, 0.083],
       [0.029, 0.673],
       [0.763, 0.842],
       ...,
       [0.434, 0.107],
       [0.737, 0.759],
       [0.082, 0.2  ]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=30000,alpha=0.0001):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if  (rating!=99): #
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)


In [0]:
sgd(30,alpha=0.0001)

26.238805939144555
25.266539373903598
24.976131558285314
24.757716991169637
24.54645447860023
24.333668139892715
24.118505458453782
23.9017203141537
23.684509310074247
23.468186144650794
23.254043291160325
23.04326614152333
22.836865464306594
22.635618415404352
22.44001472520248
22.250206134728913
22.065957387359735
21.886597514179208
21.71097161165522
21.537396573286614
21.36363015822038
21.186872147171403
21.003829239100764
20.810889736150454
20.604463354060773
20.381531969568687
20.14040857767338
19.88159800154975
19.608507715744157
19.32764475217676


In [0]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-0.568, -0.802, -1.04 , ...,  0.083, -0.614,  0.029],
       [ 2.423,  2.583,  2.753, ...,  2.064,  2.088,  2.493],
       [ 4.168,  4.014,  3.874, ...,  4.788,  3.322,  5.631],
       ...,
       [ 0.259,  0.146,  0.033, ...,  0.595,  0.141,  0.673],
       [ 0.144, -0.053, -0.25 , ...,  0.716, -0.006,  0.792],
       [ 3.389,  3.297,  3.216, ...,  3.798,  2.722,  4.475]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
#comparison_data.columns = df_del.columns

In [0]:
comparison_data

0  ...                            99
0      (-7.82, -0.568101572727384)  ...  (99.0, 0.029436083680738166)
1       (4.08, 2.4227041624961245)  ...    (99.0, 2.4930655465060614)
2        (99.0, 4.168407564162596)  ...      (99.0, 5.63131573762051)
3        (99.0, 2.281061732402889)  ...    (99.0, 2.9728176162750253)
4        (8.5, 3.2011976387101284)  ...     (99.0, 4.385926434245617)
...                            ...  ...                           ...
24978   (0.44, 1.8018404368978422)  ...     (7.43, 3.421641715903742)
24979   (99.0, 1.0376422877297902)  ...    (8.45, 0.9636964588332793)
24980    (99.0, 0.258987231946284)  ...    (99.0, 0.6727842871870804)
24981  (99.0, 0.14402479502161292)  ...    (99.0, 0.7917643515802076)
24982   (99.0, 3.3893651363650728)  ...     (99.0, 4.475254687937171)

[24983 rows x 100 columns]

In [0]:
#MSE (latent_factors=2, iterations=20, alpha=0.0001)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mse1=sum(error)/len(error)
mse1

19.8743460258999

Repeat the two points above changing hyper-parameters (i.e., learning rate, number of iterations of SVD, number of latent factors, etc.) 

1.   case1: latent_factors=2, iterations=20, alpha=0.0001
2.   case2: latent_factors=2, iterations=30, alpha=0.0001

3.   case3: latent_factors=3, iterations=20, alpha=0.0001
4.   case4: latent_factors=4, iterations=20, alpha=0.0001


In [0]:
#MSE  (latent_factors=2, iterations=30, alpha=0.0001)
n_latent_factors = 2
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=30,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mse2=sum(error)/len(error)


26.238805939144555
25.266539373903598
24.976131558285314
24.757716991169637
24.54645447860023
24.333668139892715
24.118505458453782
23.9017203141537
23.684509310074247
23.468186144650794
23.254043291160325
23.04326614152333
22.836865464306594
22.635618415404352
22.44001472520248
22.250206134728913
22.065957387359735
21.886597514179208
21.71097161165522
21.537396573286614
21.36363015822038
21.186872147171403
21.003829239100764
20.810889736150454
20.604463354060773
20.381531969568687
20.14040857767338
19.88159800154975
19.608507715744157
19.32764475217676


In [0]:
# MSE latent_factors=3, iterations=20, alpha=0.0001
n_latent_factors = 3
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=20,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mse3=sum(error)/len(error)

25.896228891227214
25.090062979896995
24.91016087978386
24.762087173415654
24.614768313594894
24.465170550882608
24.312854855272025
24.15773670669698
23.999706613715
23.8384891356854
23.673528670299596
23.503860084451247
23.327953584088846
23.14353518315484
22.947398413335527
22.7352480379253
22.501658610748795
22.240290853496678
21.94457138062199
21.60905321036611


In [0]:
# MSE latent_factors=4, iterations=20, alpha=0.0001

n_latent_factors = 4
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=20,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mse4=sum(error)/len(error)

25.732921224820494
25.007724227310742
24.876344627848784
24.76291263532542
24.649655169210263
24.535152940718525
24.419195270380605
24.301736034223737
24.182743176918784
24.062145096489797
23.93978411638455
23.815360187692733
23.688357450059126
23.55794712919915
23.422860301769557
23.28122553608914
23.130371661169736
22.966608816639233
22.785027561473754
22.579403677807644


In [0]:
print("case1: latent_factors=2, iterations=20, alpha=0.0001",mse1)

print("case2: latent_factors=2, iterations=30, alpha=0.0001",mse2)

print("case3: latent_factors=3, iterations=20, alpha=0.0001",mse3)

print("case4: latent_factors=4, iterations=30, alpha=0.0001",mse4)

case1: latent_factors=2, iterations=20, alpha=0.0001 19.8743460258999
case2: latent_factors=2, iterations=30, alpha=0.0001 19.8743460258999
case3: latent_factors=3, iterations=20, alpha=0.0001 21.946082879178032
case4: latent_factors=4, iterations=30, alpha=0.0001 22.89106685977777
