<a href="https://colab.research.google.com/github/weiyuchen1213/CE888/blob/master/my_recommender_W.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [32]:
jester_df = pd.read_csv("https://raw.githubusercontent.com/weiyuchen1213/CE888/master/Lab5/jester-data-1.csv", delimiter = ",")
jester_df

df_del = jester_df.drop(jester_df.columns[0],axis=1) #Columns "74" 
df_del

4.08  -0.29   6.36   4.37  -2.38  ...  -2.14.1   3.06   0.34  -4.32.1   1.07
0      99.00  99.00  99.00  99.00   9.03  ...    99.00  99.00  99.00    99.00  99.00
1      99.00   8.35  99.00  99.00   1.80  ...    99.00  99.00  99.00    99.00  99.00
2       8.50   4.61  -4.17  -5.39   1.36  ...     1.55   3.11   6.55     1.80   1.60
3      -6.17  -3.54   0.44  -8.50  -7.09  ...    -3.35   0.05  -9.08    -5.05  -3.45
4      99.00  99.00  99.00  99.00   8.59  ...     2.33  99.00  99.00    99.00  99.00
...      ...    ...    ...    ...    ...  ...      ...    ...    ...      ...    ...
24976   0.44   7.43   9.08   2.33   3.20  ...     9.03   6.55   8.69     8.79   7.43
24977   9.13  -8.16   8.59   9.08   0.87  ...    -8.20  -7.23  -8.59     9.13   8.45
24978  99.00  99.00  99.00  99.00  -7.77  ...    99.00  99.00  99.00    99.00  99.00
24979  99.00  99.00  99.00  99.00  -9.71  ...    99.00  99.00  99.00    99.00  99.00
24980   2.43   2.67  -3.98   4.27  -2.28  ...    99.00  99.00  99.00    99.00  99.00

[24981 rows x 100 columns]

In [0]:
arr = df_del.values
print(arr.shape)

In [4]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1810381 (1810381,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [7]:
arr

array([[ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  ,  8.35, 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [ 2.43,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

In [8]:
new_arr

array([[ 4.08, 99.  ,  6.36, ...,  0.34, -4.32,  1.07],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  ,  8.35, 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [ 2.43,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

In [9]:
arr[idx[0][0], idx[1][0]]

0.97

In [10]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [12]:
latent_item_features

array([[0.566, 0.135],
       [0.821, 0.306],
       [0.487, 0.634],
       [0.76 , 0.049],
       [0.231, 0.245],
       [0.15 , 0.79 ],
       [0.146, 0.949],
       [0.646, 0.718],
       [0.78 , 0.125],
       [0.345, 0.172],
       [0.311, 0.165],
       [0.975, 0.278],
       [0.85 , 0.325],
       [0.698, 0.565],
       [0.788, 0.926],
       [0.224, 0.406],
       [0.062, 0.516],
       [0.704, 0.625],
       [0.41 , 0.076],
       [0.82 , 0.706],
       [0.581, 0.285],
       [0.598, 0.243],
       [0.554, 0.365],
       [0.438, 0.452],
       [0.947, 0.957],
       [0.072, 0.199],
       [0.078, 0.43 ],
       [0.414, 0.25 ],
       [0.096, 0.782],
       [0.824, 0.181],
       [0.354, 0.565],
       [0.432, 0.527],
       [0.619, 0.807],
       [0.093, 0.934],
       [0.419, 0.938],
       [0.585, 0.804],
       [0.192, 0.937],
       [0.85 , 0.384],
       [0.635, 0.78 ],
       [0.699, 0.677],
       [0.244, 0.832],
       [0.363, 0.2  ],
       [0.628, 0.108],
       [0.3

In [13]:
latent_user_preferences

array([[0.863, 0.019],
       [0.73 , 0.342],
       [0.251, 0.427],
       ...,
       [0.996, 0.184],
       [0.319, 0.928],
       [0.495, 0.176]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=30000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if  (rating!=99): #
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)


In [20]:
sgd(30)

22.29681257583636
22.104941666290888
21.915678838413953
21.72734807450626
21.537634957321494
21.343594546705738
21.14173960650093
20.928267044775183
20.699489169992475
20.452517329406717
20.186173813843233
19.9019673776824
19.60478970502695
19.302888520075015
19.00681077850029
18.72744612897059
18.47382575368415
18.251540478747472
18.062316487591595
17.904666737105128
17.775090176164003
17.669255429389096
17.582849272429613
17.512036398235082
17.453624001186775
17.405054719969172
17.36432320273991
17.329872471083657
17.300496709208517
17.27525991304523


In [23]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 3.401,  3.789,  4.262, ...,  2.586,  3.979,  2.783],
       [ 6.471,  6.835,  6.828, ...,  6.714,  6.182,  7.593],
       [ 1.797,  1.765,  1.442, ...,  2.501,  1.225,  2.924],
       ...,
       [ 0.842,  0.912,  0.964, ...,  0.769,  0.886,  0.854],
       [-1.668, -2.007, -2.599, ..., -0.555, -2.502, -0.45 ],
       [ 2.843,  2.902,  2.657, ...,  3.43 ,  2.345,  3.951]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
#comparison_data.columns = df_del.columns

In [29]:
comparison_data

0  ...                            99
0       (4.08, 3.4011747639024503)  ...    (1.07, 2.7825659881588365)
1        (99.0, 6.470643529173391)  ...     (99.0, 7.592941752082429)
2       (99.0, 1.7969945409881123)  ...    (99.0, 2.9241454735922403)
3         (8.5, 3.106889027384362)  ...      (1.6, 4.304488563260059)
4      (-6.17, -4.968203621360178)  ...   (-3.45, -4.942471048338963)
...                            ...  ...                           ...
24977   (0.44, 2.0623178972625316)  ...     (7.43, 3.815221241872735)
24978   (9.13, 2.6338057538516146)  ...     (99.0, 1.491321272024949)
24979   (99.0, 0.8424595738422781)  ...    (99.0, 0.8538436405842014)
24980  (99.0, -1.6677073843866221)  ...  (99.0, -0.45023027054595743)
24981   (2.43, 2.8427669510914493)  ...       (99.0, 3.9513893296758)

[24982 rows x 100 columns]

In [0]:
Eror = [] #MSE

