In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [0]:
df = pd.read_csv("https://raw.githubusercontent.com/hsuemily/CE888_Hsu-Chi-Rou_1900759/master/Lab%205/jester-data-1.csv", delimiter = ",", header=None)
df
# add header in first row, head(), Ref:https://stackoverflow.com/questions/34091877/how-to-add-header-row-to-a-pandas-dataframe

0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]

In [0]:
arr = df.copy() 
arr = arr.drop(arr.columns[0], axis=1)

In [0]:
arr = arr.values
print(arr.shape)

(24983, 100)


In [0]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

1810455 (1810455,)


In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])


In [0]:
new_arr, idx = replace(arr, 0.1)

In [0]:
arr[idx[0][0], idx[1][0]]

5.1

In [0]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
new_arr

array([[99.  ,  8.79, -9.66, ..., 99.  , 99.  , 99.  ],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [ 2.43,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

In [0]:
arr

array([[-7.82,  8.79, -9.66, ..., 99.  , 99.  , 99.  ],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [ 2.43,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

In [0]:
#Use latent factor modeling to infer the hidden ratings of the users(they are labeled as "99" in the dataset) on the training set
#caseA1: latent_factors=2, iterations=20, alpha=0.0001
n_latent_factors = 2
user_ratings = new_arr
# Initialise as random values
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
user_ratings.shape[1]

100

In [0]:
latent_item_features

array([[0.194, 0.704],
       [0.588, 0.198],
       [0.162, 0.786],
       [0.045, 0.948],
       [0.619, 0.263],
       [0.488, 0.122],
       [0.559, 0.693],
       [0.02 , 0.267],
       [0.205, 0.997],
       [0.019, 0.628],
       [0.59 , 0.186],
       [0.894, 0.152],
       [0.924, 0.788],
       [0.543, 0.834],
       [0.62 , 0.402],
       [0.497, 0.765],
       [0.037, 0.879],
       [0.445, 0.323],
       [0.4  , 0.457],
       [0.443, 0.065],
       [0.347, 0.895],
       [0.29 , 0.904],
       [0.85 , 0.471],
       [0.037, 0.683],
       [0.347, 0.015],
       [0.771, 0.666],
       [0.931, 0.975],
       [0.438, 0.242],
       [0.703, 0.465],
       [0.34 , 0.003],
       [0.916, 0.23 ],
       [0.716, 0.095],
       [0.422, 0.691],
       [0.715, 0.482],
       [0.117, 0.644],
       [0.641, 0.09 ],
       [0.347, 0.171],
       [0.925, 0.884],
       [0.357, 0.744],
       [0.781, 0.857],
       [0.757, 0.514],
       [0.506, 0.215],
       [0.78 , 0.949],
       [0.2

In [0]:
latent_item_features.shape[0]

100

In [0]:
latent_user_preferences

array([[4.170e-01, 7.203e-01],
       [1.144e-04, 3.023e-01],
       [1.468e-01, 9.234e-02],
       ...,
       [4.237e-01, 2.855e-01],
       [3.626e-01, 2.645e-03],
       [6.934e-01, 9.607e-01]])

In [0]:
latent_user_preferences.shape[0]

24983

In [0]:

def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=1000, alpha=0.0001):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if (rating!=99):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 1) == 0:
            print(mse)

In [0]:
# caseA1: latent_factors=2, iterations=20, alpha=0.0001
sgd(iterations=20, alpha=0.0001)  # Note how the MSE decreases with the number of iterations

26.255155595072157
25.285005249168833
24.995692485441047
24.778215829332698
24.567815370096774
24.355834466364666
24.1414275893022
23.925352660882254
23.708813311891426
23.493137565684474
23.27964316252281
23.06955534803058
22.86394338195138
22.66366627959249
22.469324601980006
22.28121644235144
22.09929574964916
21.923131082182486
21.75186347056581
21.58416386209072


In [0]:
predictions = latent_user_preferences.dot(latent_item_features.T)

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
# comparison_data.columns = new_arr.columns

In [0]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

0  ...                           99
0       (99.0, 1.2711773250929317)  ...   (99.0, 1.7948443542576982)
1       (4.08, 1.1746508171501526)  ...   (1.07, 1.5615031827554746)
2       (99.0, 2.5891728573085055)  ...   (99.0, 3.7812515292205733)
3       (99.0, 1.7410701960845147)  ...   (99.0, 2.4726869627593375)
4         (8.5, 2.686708233872093)  ...   (99.0, 3.8600098702750305)
...                            ...  ...                          ...
24978   (0.44, 2.4201272372202984)  ...   (7.43, 3.7543640192029266)
24979  (9.13, 0.11223154543845318)  ...  (99.0, 0.21718343719944203)
24980   (99.0, 0.2911787833717565)  ...  (99.0, 0.48149681535299654)
24981   (99.0, 0.5417356377516905)  ...   (99.0, 0.9284232456847992)
24982   (2.43, 2.9393884131227237)  ...    (99.0, 4.184834238633287)

[24983 rows x 100 columns]

In [0]:
# Calculate the performance (e.g., MSE) of the algorithm on the validation dataset
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseA1=sum(error)/len(error)
print("caseA1: ",mseA1)

caseA1:  21.814225966782008


### Repeat the two points above changing hyper-parameters (i.e., learning rate, number of iterations of SVD, number of latent factors, etc.) as needed to get good results (you can create multiple validation sets if you want, and run a bootstrap!)

In [0]:
# caseA2: latent_factors=2, iterations=30, alpha=0.0001
n_latent_factors = 2
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=30,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseA2=sum(error)/len(error)
print("caseA2: ",mseA2)

26.255155595072157
25.285005249168833
24.995692485441047
24.778215829332698
24.567815370096774
24.355834466364666
24.1414275893022
23.925352660882254
23.708813311891426
23.493137565684474
23.27964316252281
23.06955534803058
22.86394338195138
22.66366627959249
22.469324601980006
22.28121644235144
22.09929574964916
21.923131082182486
21.75186347056581
21.58416386209072
21.418194286139585
21.2515832052654
21.081435169543
20.90440771542267
20.71690194247088
20.5154201259297
20.297129916381856
20.060620692584017
19.806730741817525
19.539184369647714
caseA2:  19.941322774431992


In [0]:
# caseA3: latent_factors=2, iterations=40, alpha=0.0001
n_latent_factors = 2
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseA3=sum(error)/len(error)
print("caseA3: ",mseA3)

26.255155595072157
25.285005249168833
24.995692485441047
24.778215829332698
24.567815370096774
24.355834466364666
24.1414275893022
23.925352660882254
23.708813311891426
23.493137565684474
23.27964316252281
23.06955534803058
22.86394338195138
22.66366627959249
22.469324601980006
22.28121644235144
22.09929574964916
21.923131082182486
21.75186347056581
21.58416386209072
21.418194286139585
21.2515832052654
21.081435169543
20.90440771542267
20.71690194247088
20.5154201259297
20.297129916381856
20.060620692584017
19.806730741817525
19.539184369647714
19.264685397591787
18.992189728097102
18.731388493236768
18.49085181730687
18.276519003003205
18.091058663363793
17.934165588061827
17.803449442057122
17.69544915586812
17.606446650172757
caseA3:  18.415348081932063


In [0]:
# caseB1: latent_factors=3, iterations=20, alpha=0.0001
n_latent_factors = 3
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseB1=sum(error)/len(error)
print("caseB1: ",mseB1)

25.912527845872393
25.107793114857163
24.928829977443076
24.78147958902412
24.63482348745286
24.485873181962866
24.334204966884073
24.179742858115162
24.022386455873907
23.861872904610156
23.69766432849722
23.528819496458727
23.353838931591685
23.170484109829925
22.975585095948514
22.76487541775102
22.532934560406957
22.273379094438013
21.979509181891075
21.64563717510605
21.269193686139396
20.853297781928045
20.408806880128914
19.954340250765537
19.513182124105263
19.107679717712028
18.753680841583453
18.457775487546566
18.218172207137293
18.027810911583597
17.87766032889414
17.758974896879412
17.664351631369946
17.587966274324874
17.525411958765535
17.47341484321738
17.42955655109938
17.392046963468168
17.35955193931074
17.331067271305795
caseB1:  18.182712769916694


In [0]:
# caseB2: latent_factors=4, iterations=30, alpha=0.0001
n_latent_factors = 4
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseB2=sum(error)/len(error)
print("caseB2: ",mseB2)

25.753614199392526
25.030634087316464
24.899755609556934
24.786630245977545
24.673606795309524
24.559277276982726
24.44341908710098
24.32596217404777
24.206837298067814
24.085917598616454
23.96296460050751
23.83756130730792
23.709024212373944
23.576286965056017
23.437749047629644
23.29108590520068
23.133025852164984
22.959119151572672
22.763563673662546
22.53921710178038
22.278015523075226
21.972097109490864
21.615894323009638
21.209130024752767
20.759901715604666
20.286121145916567
19.813415824111235
19.36918443224336
18.975265784909414
18.643080845539615
18.373376899488438
18.159510400990097
17.991605663770027
17.85964255677232
17.755002233917185
17.67088513761335
17.602163613381563
17.545050542850873
17.49676650526662
17.455266931625225
caseB2:  18.237921111943187


In [0]:
# caseB3: latent_factors=5, iterations=40, alpha=0.0001
n_latent_factors = 5
user_ratings = new_arr
np.random.seed(1)
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
sgd(iterations=40,alpha=0.0001)
predictions = latent_user_preferences.dot(latent_item_features.T)
error = (predictions[idx[0][:],idx[1][:]]-arr[idx[0][:],idx[1][:]])**2
mseB3=sum(error)/len(error)
print("caseB3: ",mseB3)

25.59210782390128
24.985847704849615
24.884262481078025
24.791746596055138
24.699340729782534
24.606239930011327
24.51211116732924
24.416673640741184
24.319608326129806
24.22048899102312
24.11870098456272
24.01333522461961
23.903045908275793
23.78586027997168
23.6589312454514
23.518233336634037
23.35822767930709
23.1715751497703
22.94907410448607
22.680143243341746
22.35431302861642
21.9641629976346
21.509631235795993
21.002381647767326
20.467427240556457
19.939184964535816
19.45217083511495
19.03098337958683
18.68532781973734
18.411833097733773
18.199662059877717
18.035899762628286
17.90876899651634
17.808807630566626
17.728886719715824
17.66379401743067
17.609758404225463
17.56405025144203
17.524680991649202
17.490187474240162
caseB3:  18.244932765181957
