<a href="https://colab.research.google.com/github/weiyuchen1213/CE888/blob/master/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [0]:
jester_df = pd.read_csv("https://raw.githubusercontent.com/weiyuchen1213/CE888/master/Lab5/jester-data-1.csv", delimiter = ",")
jester_df

df_del = jester_df.drop(jester_df.columns[0],axis=1) #Columns "74" 
df_del

In [0]:
arr = df_del.values
print(arr.shape)

In [0]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

In [0]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [0]:
new_arr, idx = replace(arr, 0.1)

In [0]:
arr

array([[ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  ,  8.35, 99.  , ..., 99.  , 99.  , 99.  ],
       ...,
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [99.  , 99.  , 99.  , ..., 99.  , 99.  , 99.  ],
       [ 2.43,  2.67, -3.98, ..., 99.  , 99.  , 99.  ]])

In [0]:
new_arr

array([[100.  ,   4.08,  -0.29, ...,  99.  ,  99.  ,   1.07],
       [ 99.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 48.  ,  99.  ,   8.35, ...,  99.  ,  99.  ,  99.  ],
       ...,
       [ 39.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 37.  ,  99.  ,  99.  , ...,  99.  ,  99.  ,  99.  ],
       [ 99.  ,   2.43,   2.67, ...,  99.  ,  99.  ,  99.  ]])

In [0]:
arr[idx[0][0], idx[1][0]]

1.21

In [0]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [0]:
n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [0]:
latent_item_features

array([[ 5.984e+01,  6.071e+01],
       [ 1.848e+00, -3.984e-01],
       [ 1.376e+00, -7.815e-01],
       [ 1.533e+00, -9.180e-01],
       [ 6.233e-01, -2.404e+00],
       [ 1.201e+00, -3.857e-01],
       [ 2.624e+00, -1.492e-01],
       [ 3.454e-01, -7.592e-01],
       [-4.764e-02, -7.198e-01],
       [ 1.172e+00, -1.864e+00],
       [ 2.006e+00, -1.867e-02],
       [ 2.460e+00,  3.994e-01],
       [ 2.238e+00,  1.722e-01],
       [-7.635e-01, -1.837e+00],
       [ 2.370e+00, -2.524e-02],
       [-8.145e-01, -1.754e+00],
       [-1.490e+00, -3.140e+00],
       [-1.748e-01, -1.313e+00],
       [ 2.025e-01, -1.073e+00],
       [ 1.072e+00, -6.213e-01],
       [ 2.538e-01, -1.525e+00],
       [ 2.845e+00,  6.714e-01],
       [ 2.067e+00, -5.625e-01],
       [ 1.487e+00, -1.126e+00],
       [ 5.889e-01, -2.779e+00],
       [ 1.610e+00, -7.746e-01],
       [ 2.168e+00,  3.170e-02],
       [ 3.202e+00,  1.824e+00],
       [ 2.465e+00,  1.819e-02],
       [ 2.987e+00,  1.803e+00],
       [ 1

In [0]:
latent_user_preferences

array([[0.893, 0.709],
       [1.365, 0.985],
       [0.411, 0.416],
       ...,
       [0.311, 0.317],
       [0.246, 0.384],
       [0.972, 0.898]])

In [0]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  prediction_rating - rating
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations=10000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if  (rating!=99): #
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10) == 0:
            print(mse)


In [0]:
sgd(1000)

23.317996759523073
18.498982344035728
17.956203689309895
17.904767394132328
17.89182066036718


In [0]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 9.665e+01,  1.144e+00,  4.399e-01, ...,  1.017e+00,  1.022e-01,
         1.512e+00],
       [ 1.220e+02,  1.496e+00,  5.841e-01, ...,  1.382e+00,  2.926e-01,
         2.072e+00],
       [ 4.983e+01,  5.816e-01,  2.224e-01, ...,  5.096e-01,  2.765e-02,
         7.548e-01],
       ...,
       [ 3.781e+01,  4.586e-01,  1.783e-01, ...,  4.193e-01,  7.551e-02,
         6.269e-01],
       [ 3.792e+01,  4.273e-01,  1.608e-01, ...,  3.589e-01, -2.740e-02,
         5.263e-01],
       [ 1.012e+02,  1.194e+00,  4.588e-01, ...,  1.059e+00,  9.732e-02,
         1.574e+00]])

In [0]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns

ValueError: ignored

In [0]:
comparison_data

0  ...                          100
0       (100.0, 96.59058309149052)  ...   (1.07, 1.4754230527217853)
1        (99.0, 98.55500477453235)  ...   (99.0, 1.6034106493741571)
2        (48.0, 49.79198045300492)  ...   (99.0, 0.7562648385097989)
3        (91.0, 93.91297546108312)  ...    (1.6, 1.4705596469693691)
4       (100.0, 91.73108523988357)  ...  (-3.45, 1.2518040586143022)
...                            ...  ...                          ...
24977  (100.0, 102.93494362367456)  ...   (7.43, 1.7508428502723299)
24978     (91.0, 85.2930232956059)  ...    (8.45, 1.220349876082886)
24979   (39.0, 37.862475905170335)  ...   (99.0, 0.6058585926248712)
24980   (37.0, 37.962478419156646)  ...   (99.0, 0.5493386259912297)
24981    (99.0, 86.72848594993147)  ...   (99.0, 1.3296419075029153)

[24982 rows x 101 columns]